"use client";
import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { EmployeeFormType } from "@/types/employee";
import { addNewEmployee } from "@/domain/employee/new.employee";

export default function AddStudent() {
	const { register, handleSubmit } = useForm<EmployeeFormType>();

	useEffect(() => {
		const today = new Date();
		const maxDateObj = new Date(today);
		maxDateObj.setFullYear(today.getFullYear() - 18);

		const year = maxDateObj.getFullYear();
		const month = String(maxDateObj.getMonth() + 1).padStart(2, "0");
		const day = String(maxDateObj.getDate()).padStart(2, "0");

		const maxDateString = `${year}-${month}-${day}`;

		const dateInput = document.getElementById("date_of_birth") as HTMLInputElement;
		if (dateInput) {
			dateInput.max = maxDateString;
		}
	}, []);

	const submit = (data: EmployeeFormType) => {
		data.date_of_birth = new Date(data.date_of_birth).toISOString();
		const response: Promise<any> = addNewEmployee(data);

		response.then((data) => {
			if (data?.success) {
				alert(data.msg);
				const form = document.getElementById("reg-form") as HTMLFormElement;
				form.reset();
			}
		});
	};

	return (
		<form id="reg-form" onSubmit={handleSubmit(submit)} className="px-1 py-10 grid gap-10">
			<section className="grid gap-10 bg-white p-7 rounded-2xl">
				<header className="px-5 py-1 border-l-5 border-l-red-theme-400">
                    <h1 className="text-red-theme-400 uppercase text-xl font-bold">Staff Information</h1>
				</header>
				<main className="grid gap-10">
					<div className="grid gap-4 min-[600px]:grid-cols-2 min-[900px]:grid-cols-3">
						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="full_name">
								Staff Id Number <span className="text-[#ff0053] font-bold">(autogenerated)</span>
							</label>
							<input type="text" disabled className="p-3.5 border-none bg-[#f5f5f5] text-[#999] rounded-[.7em] w-full outline-theme-light" value="EMP-RANDOM" />
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="full_name">
								Full Legal Name <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="text" {...register("full_name", { required: true })} id="full_name" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em] w-full outline-theme-light" />
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="date_of_birth">
								Date of Birth <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="date" {...register("date_of_birth", { required: true, valueAsDate: true })} id="date_of_birth" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em] outline-theme-light" />
						</div>
					</div>
					<div className="grid gap-4 min-[600px]:grid-cols-2 min-[900px]:grid-cols-3">
						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="gender">
								Gender <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<select {...register("gender", { required: true })} id="gender" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em]">
								<option value="MALE">Male</option>
								<option value="FEMALE">Female</option>
							</select>
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="nationality">
								Nationality <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="text" {...register("nationality", { required: true })} id="nationality" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em] outline-theme-light" />
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="national_id">
								National ID Number <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="text" {...register("national_id", { required: true })} id="national_id" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em] outline-theme-light" />
						</div>
					</div>

					<div className="grid gap-4">
						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="additional_information">
								Additional Information (optional)
							</label>
							<textarea {...register("additional_information")} id="additional_information" placeholder="Enter any other information" className="p-3.5 border-none bg-[#f5f5f5] outline-theme-light rounded-[.7em] min-h-[100px] max-h-[300px]"></textarea>
						</div>
					</div>
				</main>
			</section>

			<section className="grid gap-10 bg-white p-7 rounded-2xl">
				<header className="px-5 py-1 border-l-5 border-l-red-theme-400">
					<h1 className="text-red-theme-400 uppercase text-xl font-bold">Employment Information</h1>
				</header>
				<main className="grid gap-10">
					<div className="grid gap-4 min-[600px]:grid-cols-2 min-[900px]:grid-cols-3">
						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="role">
								Role/Position <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<select {...register("role", { required: true })} id="role" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em]">
								<option value="HEADMASTER">Headmaster</option>
								<option value="DEPUTY_HEADMASTER">Deputy Headmaster</option>
								<option value="TEACHER">Teacher</option>
								<option value="SECRETARY">Secretary</option>
								<option value="BURSAR">Bursar</option>
								<option value="LIBRARIAN">Librarian</option>
								<option value="SECURITY">Security</option>
								<option value="CLEANER">Cleaner</option>
								<option value="DRIVER">Driver</option>
								<option value="CHEF">Chef</option>
							</select>
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="employment_type">
								Employment Type<span className="text-[#ff0053] font-bold">*</span>
							</label>
							<select {...register("employment_type", { required: true })} id="employment_type" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em]">
								<option value="Full-Time" selected>
									Full-Time
								</option>
								<option value="Part-Time">Part-Time</option>
								<option value="Contract">Contract/Temporary</option>
							</select>
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="department">
								Department <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<select {...register("department", { required: true })} id="department" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em]">
								<option value="ADMINISTRATION" selected>
									Administration
								</option>
								<option value="MATHEMATICS">Mathematics</option>
								<option value="SCIENCE">Science</option>
								<option value="HUMANITIES">Humanities</option>
								<option value="ARTS_SPORTS">Arts & Sports</option>
								<option value="FINANCE">Finance</option>
								<option value="COUNSELING">Counseling</option>
								<option value="IT SUPPORT">IT Support</option>
								<option value="Maintenance/Facilities">Maintenance/Facilities</option>
								<option value="OTHER">Other</option>
							</select>
						</div>
					</div>
				</main>
			</section>

			<section className="grid gap-10 bg-white p-7 rounded-2xl">
				<header className="px-5 py-1 border-l-5 border-l-red-theme-400">
					<h1 className="text-red-theme-400 uppercase text-xl font-bold">Qualification & Experience</h1>
				</header>
				<main className="grid gap-10">
					<div className="grid gap-4 min-[600px]:grid-cols-2 min-[900px]:grid-cols-3">
						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="qualification">
								Highest Qualification <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="text" {...register("qualification", { required: true })} placeholder="e.g. BTech, Phd, BCE in Computer Science" id="qualification" className="p-3.5 border-none bg-[#f5f5f5] w-full rounded-[.7em] outline-theme-light" />
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="specialization">
								Specialization <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="text" {...register("specialization", { required: true })} id="specialization" className="p-3.5 border-none bg-[#f5f5f5] w-full rounded-[.7em] outline-theme-light" />
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="experience">
								Years of Experience <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="number" {...register("experience", { required: true, valueAsNumber: true })} min={1} id="experience" className="p-3.5 border-none bg-[#f5f5f5] w-full rounded-[.7em] outline-theme-light" />
						</div>
					</div>
				</main>
			</section>

			<section className="grid gap-10 bg-white p-7 rounded-2xl">
				<header className="px-5 py-1 border-l-5 border-l-red-theme-400">
					<h1 className="text-red-theme-400 uppercase text-xl font-bold">Contact Information</h1>
				</header>
				<main className="grid gap-10">
					<div className="grid gap-4 min-[600px]:grid-cols-2 min-[900px]:grid-cols-3">
						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="phone_number">
								Phone Number <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="tel" {...register("phone_number", { required: true })} id="phone_number" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em] outline-theme-light" />
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="email_address">
								Email Address<span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="email" {...register("email_address", { required: true })} id="email_address" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em] outline-theme-light" />
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="residential_address">
								Residential Address
							</label>
							<input type="text" {...register("residential_address")} id="residential_address" placeholder="Enter full address" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em] outline-theme-light" />
						</div>
					</div>

					<div className="grid gap-4 min-[600px]:grid-cols-2 min-[900px]:grid-cols-3">
						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="emergency_contact_name">
								Emergency Contact Name <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="tel" {...register("emergency_contact_name", { required: true })} id="emergency_contact_name" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em] outline-theme-light" />
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="emergency_contact_number">
								Emergency Phone Number <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="tel" {...register("emergency_contact_number", { required: true })} id="emergency_contact_number" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em] outline-theme-light" />
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="emergency_contact_relationship">
								Emergency Contact Relationship <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="tel" {...register("emergency_contact_relationship", { required: true })} id="emergency_contact_relationship" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em] outline-theme-light" />
						</div>
					</div>
				</main>
			</section>

			<section className="grid gap-10 bg-white p-7 rounded-2xl">
				<header className="px-5 py-1 border-l-5 border-l-red-theme-400">
					<h1 className="text-red-theme-400 uppercase text-xl font-bold">Payroll & Benefits</h1>
				</header>
				<main className="grid gap-10">
					<div className="grid gap-4 min-[600px]:grid-cols-2 min-[900px]:grid-cols-3">
						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="salary_amount">
								Gross Annual / Monthly Salary <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="number" {...register("salary_amount", { required: true })} placeholder="e.g. 45000.00" id="salary_amount" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em] w-full outline-theme-light" />
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="pay_frequency">
								Pay Frequency <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<select {...register("pay_frequency", { required: true })} id="pay_frequency" className="p-3.5 border-none bg-[#f5f5f5] w-full rounded-[.7em]">
								<option value="MONTHLY">Monthly</option>
								<option value="WEEKLY">Weekly</option>
								<option value="BI-WEEKLY">Bi-Weekly</option>
								<option value="DAILY">Daily</option>
							</select>
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="bank_name">
								Bank Name <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="string" {...register("bank_name", { required: true })} placeholder="e.g. Standard Bank" id="bank_name" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em] w-full outline-theme-light" />
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="account_holder_name">
								Account Holder&apos;s Name <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="tel" {...register("account_holder_name", { required: true })} id="account_holder_name" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em] w-full outline-theme-light" />
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="bank_account_number">
								Bank Account Number <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="tel" {...register("bank_account_number", { required: true })} id="bank_account_number" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em] w-full outline-theme-light" />
						</div>

						<div className="grid gap-2">
							<label className="text-[#777" htmlFor="tax_number">
								Tax Identification Number (e.g., Tax Number, SSN) <span className="text-[#ff0053] font-bold">*</span>
							</label>
							<input type="tel" {...register("tax_number", { required: true })} id="tax_number" className="p-3.5 border-none bg-[#f5f5f5] rounded-[.7em] w-full outline-theme-light" />
						</div>
					</div>
				</main>
			</section>

			<div className="flex gap-3 py-5">
				<button type="reset" className="p-5 px-7 cursor-pointer bg-[#eee] rounded-full text-theme">
					Clear Form
				</button>
				<button type="submit" className="p-5 px-7 cursor-pointer bg-red-theme-400 rounded-full text-white">
					Submit Application
				</button>
			</div>
		</form>
	);
}
